CREATE TABLE Users (
	Id SERIAL PRIMARY KEY,
	Username VARCHAR(128) UNIQUE NOT NULL,
	Password VARCHAR NOT NULL,
	visible INTEGER DEFAULT 1);

CREATE TABLE Book (
	Id SERIAL PRIMARY KEY,
	Title VARCHAR(128) NOT NULL,
	Author VARCHAR(128) NOT NULL,
	Publication_year INTEGER,
	ISBN VARCHAR(64),
	Pages INTEGER,
	Comment VARCHAR,
	User_id INTEGER NOT NULL,
	visible INTEGER DEFAULT 1,
       	FOREIGN KEY (User_id) REFERENCES Users(Id));

CREATE TABLE Video (
	Id SERIAL PRIMARY KEY,
	Title VARCHAR(128),
	Source VARCHAR NOT NULL,
	Upload_date DATE,
	Comment VARCHAR,
	User_id INTEGER NOT NULL,
	visible INTEGER DEFAULT 1,
	FOREIGN KEY (User_id) REFERENCES Users(Id));
